spring:
  application:
    name: screenmatch

datasource:
  url: jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabase:IfNotExist=true
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: none
  show-sql: true
  properties:
    hibernate:
      format_sql: true

server:
  error:
    include-stacktrace: never

flyway:
  enabled: true
  locations: classpath:db/migration

omdb:
  api:
    key:  "${OMDB_API_KEY}"
    url:  "https://www.omdbapi.com/"





